# coding: utf-8
root: /
permalink: /:categories/:year/:month/:day/:title/
paginate: 10
title: Blog | Fantasy
description: A blog on programming, learning and reading.
author: Fantasy Shao
email: fantasyshao@icloud.com
subscribe_rss: /atom.xml
license: true
category_list: true
links: true
address: http://blog.fantasy.codes
url: http://blog.fantasy.codes
plugins:
  - jekyll-paginate
  - jekyll-admin
