root: /
permalink: /:year-:month-:title/
markdown: rdiscount
pygments: true 
paginate: 5
excerpt_link: "阅读更多 &rarr;"

title: fantasy | blog
author: fanTasy shAo
subscribe_rss: /atom.xml
license: true
category_list: true
links: true
google_analytics_tracking_id: UA-36896790-1

#Generate css
#compass compile

