# coding: utf-8 
root: /
permalink: /:year-:month-:title/
markdown: rdiscount
pygments: true 
paginate: 12

#title: Blog - fantasyshao
author: fanTasy shAo
subscribe_rss: /atom.xml
license: true
category_list: true
links: true
url: http://blog.fantasyshao.com
#google_analytics_tracking_id: UA-36896790-1

#Generate css
#compass compile
