root: /
permalink: /:year-:month-:title/
markdown: rdiscount
pygments: true 
paginate: 10

title: Fantasy's Homepage
author: fanTasy shAo
subscribe_rss: /atom.xml
license: true
category_list: true
links: true
#google_analytics_tracking_id: UA-36896790-1

#Generate css
#compass compile

