# coding: utf-8 
root: /
permalink: /:year-:month-:title/
markdown: rdiscount
pygments: true 
paginate: 30

title: Blog | Fantasy
author: fanTasy shAo
subscribe_rss: /atom.xml
license: true
category_list: true
links: true
url: http://www.shaofantasy.cn
#google_analytics_tracking_id: UA-36896790-1

#Generate css
#compass compile
