# coding: utf-8
root: /
permalink: /:categories/:year/:month/:day/:title/
markdown: rdiscount
highlighter: pygments
paginate: 12

title: Blog | Fantasy
author: Fantasy Shao
email: fantasyshao@icloud.com
subscribe_rss: /atom.xml
license: true
category_list: true
links: true
address: http://blog.fantasy.codes
url: http://blog.fantasy.codes
